### ISSUE TITLE
Variational routing assumes fully connected child-parent relationships?

### ISSUE THREAD

**Issue by Parskatt** [fabio-deep/Variational-Capsule-Routing#1]
I was under the impression that you performed convolutional routing, i.e. only routing between child-parents within the parents receptive field, but from looking into your code it looks like the routing is always fully connected or am I misunderstanding something?

VariationalBayesRouting2d.py forward method looks like this:

```python
    # Out ← [?, B, 1, 1, 1, F, F, K, K], [?, B, C, P*P, 1, F, F, K, K] ← In
    def forward(self, a_i, V_ji):

        self.F_i = a_i.shape[-2:] # input capsule (B) votes feature map size (K)
        self.F_o = a_i.shape[-4:-2] # output capsule (C) feature map size (F)
        self.N = self.B*self.F_i[0]*self.F_i[1] # total num of lower level capsules

        # Out ← [1, B, C, 1, 1, 1, 1, 1, 1]
        R_ij = (1./self.C) * torch.ones(1,self.B,self.C,1,1,1,1,1,1, requires_grad=False).cuda()

        for i in range(self.iter): # routing iters

            # update capsule parameter distributions
            self.update_qparam(a_i, V_ji, R_ij)

            if i != self.iter-1: # skip last iter
                # update latent variable distributions (child to parent capsule assignments)
                R_ij = self.update_qlatent(a_i, V_ji)

        # Out ← [?, 1, C, 1, 1, F, F, 1, 1]
        self.Elnlambda_j = self.reduce_poses(
            torch.digamma(.5*(self.nu_j - self.diga_arg))) \
                + self.Dlog2 + self.lndet_Psi_j

        # Out ← [?, 1, C, 1, 1, F, F, 1, 1]
        self.Elnpi_j = torch.digamma(self.alpha_j) \
            - torch.digamma(self.alpha_j.sum(dim=2, keepdim=True))

        # subtract "- .5*ln|lmbda|" due to precision matrix, instead of adding "+ .5*ln|sigma|" for covariance matrix
        H_q_j = .5*self.D * torch.log(torch.tensor(2*np.pi*np.e)) - .5*self.Elnlambda_j # posterior entropy H[q*(mu_j, sigma_j)]

        # Out ← [?, 1, C, 1, 1, F, F, 1, 1] weighted negative entropy with optional beta params and R_j weight
        a_j = self.beta_a - (torch.exp(self.Elnpi_j) * H_q_j + self.beta_u) #* self.R_j

        # Out ← [?, C, F, F]
        a_j = a_j.squeeze()

        # Out ← [?, C, P*P, F, F] ← [?, 1, C, P*P, 1, F, F, 1, 1]
        self.m_j = self.m_j.squeeze()

        # so BN works in the classcaps layer
        if self.class_caps:
            # Out ← [?, C, 1, 1] ← [?, C]
            a_j = a_j[...,None,None]

            # Out ← [?, C, P*P, 1, 1] ← [?, C, P*P]
            self.m_j = self.m_j[...,None,None]
        # else:
        #     self.m_j = self.BN_v(self.m_j)

        # Out ← [?, C, P*P, F, F]
        self.m_j = self.BN_v(self.m_j) # use 'else' above to deactivate BN_v for class_caps

        # Out ← [?, C, P, P, F, F] ← [?, C, P*P, F, F]
        self.m_j = self.m_j.reshape(-1, self.C, self.P, self.P, *self.F_o)

        # Out ← [?, C, F, F]
        a_j = torch.sigmoid(self.BN_a(a_j))

        return a_j.squeeze(), self.m_j.squeeze() # propagate posterior means to next layer
```

If I'm reading this correctly, this seems like fc routing, but I might have misunderstood something. Could you explain this a bit?

**Comment by fabio-deep** [comment]
Hello, my apologies for the confusion. I think it will become clearer once you take a close look at the ConvCapsules2d layer in layers.py and track the change in tensor shapes. 

The important part is to keep an eye on the kernel size K and feature map size F. In the example provided, I use a convcaps layer as dense caps by setting the kernel size to be equal to the input feature map size coming from the preceding layer. If you set the kernel size to be equal to e.g. 3, then it will do convolution routing as we reduce over child capsules regardless of receptive field size.

Hope that helps, let me know if you have any more questions :)

**Comment by Parskatt** [comment]
Ah, so F represents the spatial dimensions and K the kernel size? And these are generated by the unfolding from the conv layer?

I have also tried using unfolding before, but I found that the tensors generated became really big for larger networks, have you have any such issues i.e. slow training when spatial dimensions are big?

**Comment by fabio-deep** [comment]
Yes and yes that's correct. As for it being slow, I haven't really compared it to alternatives so I'm not sure, but it's something you could try out and see if you can get speed improvements
