### ISSUE TITLE
Parent Capsules at different positions don't compete for child capsules?

### ISSUE THREAD

**Issue by Parskatt** [fabio-deep/Variational-Capsule-Routing#2]
Your routing seems to suffer from a common issue of normalizing for each spatial location in the parent feature map seperately.
The issue is described in more detail in section 2.3 of [Avoiding Implementation Pitfalls of "Matrix Capsules with EM Routing" by Hinton et al](https://arxiv.org/pdf/1907.00652.pdf). They solve the issue by using a special _spatial routing map_.

If you in fact take the spatial locations into account, could you explain how the normalization in your routing works?

**Comment by fabio-deep** [comment]
Hello, apologies for the delay as I have been away at a conference.
You are correct, my first commit only provided support for dense routing since there was only 1 caps layer. I've just updated the source code along with a 3 layer capsnet example so it should all be clearer now :)
