### ISSUE TITLE
variation capsule routing code

### ISSUE THREAD

**Issue by superCandy-star** [fabio-deep/Variational-Capsule-Routing#4]
I read the code of your paper, and I don’t know much about some of the codes and formulas. I hope you can explain it to me.
I will be very grateful for your advice.I am a rookie and hope to get your instructment.In your code,you proposed that initialise capsule priors  j : α0; m0; κ0; S0; ν0.I don't understand what the sign represents alone.

**Comment by fabio-deep** [comment]
Hi, 

I would recommend referring to the paper closely as I tried to keep the variable names in the code consistent with the notation used in the paper. 

If you still have questions or would like more details you can email me: fdesousaribeiro@lincoln.ac.uk.

Regards, 
Fabio
