### ISSUE TITLE
two self.D

### ISSUE THREAD

**Issue by Add2seconds** [fabio-deep/Variational-Capsule-Routing#5]
Hi, I find that in src/capsnet.py, line 15
```
self.D = int(np.max([2, self.P*self.P]))
self.A, self.B, self.C, self.D = arch[:-1]
```
There are two self. D
one is the dimension of the pose matrix, while the other is the num caps

**Comment by fabio-deep** [comment]
Thank you for spotting it, I have corrected it now!
It must have happened when I adapted the 1 layer capsnet example to 3 layers.

Thanks again, closing :)
